name: Test Writer Starter
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Tests on Writer
        uses: cypress-io/github-action@v1
        with:
          env:
            SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
            SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
            SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
          start: yarn workspace gatsby-starter-catalyst-writer develop
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
