name: Test Docs Site
on:
  push:
    branches:
      - master
    paths:
      - "www/**"
      - ".github/**"
  pull_request:
    branches:
      - master
    paths:
      - "www/**"
      - ".github/**"
jobs:
  test_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build:www
      - name: Run Tests on Core
        uses: cypress-io/github-action@v1
        with:
          start: yarn serve:www
          spec: cypress/e2e/docs.test.js
