name: Test Themes
on:
  push:
    branches:
      - master
    paths:
      - "starters/**"
      - "themes/**"
      - ".github/**"
  pull_request:
    branches:
      - master
    paths:
      - "starters/**"
      - "themes/**"
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Tests on Core
        uses: cypress-io/github-action@v1
        with:
          start: yarn workspace gatsby-starter-catalyst-core develop
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
      - name: Run Tests on Basic
        uses: cypress-io/github-action@v1
        with:
          start: yarn workspace gatsby-starter-catalyst-basic develop
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
      - name: Run Tests on Blog
        uses: cypress-io/github-action@v1
        with:
          start: yarn workspace gatsby-starter-catalyst-blog develop
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
      - name: Run Tests on Writer
        uses: cypress-io/github-action@v1
        env:
          SANITY_PROJECT_ID: ${{ secrets.SANITY_PROJECT_ID }}
          SANITY_DATASET: ${{ secrets.SANITY_DATASET }}
          SANITY_TOKEN: ${{ secrets.SANITY_TOKEN }}
        with:
          start: yarn workspace gatsby-starter-catalyst-writer develop
          wait-on: "http://localhost:8000"
          wait-on-timeout: 120
